app/models.py
""" Database models. """
from . import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash



class User(UserMixin, db.Model):
    """User account Model."""

    __tablename__ = 'flasklogin-users'
    id = db.Column(
            db.Integer,
            primary_key=True
    )
    name = db.Column(
            db.String(100),
            nullable=False,
            unique=False
            )
    email = db.Column(
            db.String(40),
            nullable=False,
            unique=True
            )
    password = db.Column(
            db.String(200),
            primary_key=False,
            unique=False,
            nullable=False
            )
    website = db.Column(
            db.String(60),
            index=False,
            unique=False,
            nullable=True
            )
    created_on = db.Column(
            db.DateTime,
            index=False,
            unique=False,
            nullable=True
            )
    last_login = db.Column(
            db.DateTime,
            index=False,
            unique=False,
            nullable=True
            )
    
    def set_password(self, password):
        """Create hashed password."""
        self.password = generate_password_hash(
           password,
           method='sha256'
        )

    def check_password(self, password):
        """check hashed password."""
        return check_password_hash(self.password, password)

    def __repr__(self):
        return '<User {}>'.format(self.username)

app/forms.py
"""Sign-up & log-in forms."""
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import (
    DataRequired,
    Email,
    EqualTo,
    Length,
    Optional
)

class SignupForm(FlaskForm):
    """User Sign-up Form."""
    name = StringField(
        'Name',
        validators=[DataRequired()]
    )
    email = StringField(
        'Email',
        validators=[
            Length(min=6),
            Email(message='Enter a valid email.'),
            DataRequired()
        ]
    )
    password = PasswordField(
        'Password',
        validators=[
            DataRequired(),
            Length(min=6, message='Select a stronger password.')
        ]
    )
    confirm = PasswordField(
        'Confirm You Password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Password must match.')
        ]
    )
    website = StringField(
        'Website',
        validators=[Optional()]
    )
    submit = SubmitField('Register')


class LoginForm(FlaskForm):
    """User Log-in Form."""
    email = StringField(
        'Email',
        validators=[
            DataRequired(),
            Email(message='Enter a valid email.')
        ]
    )
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log in')

app/__init__.py
"""Initialize app."""

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_wtf.csrf import CSRFProtect

db = SQLAlchemy()
login_manager = LoginManager()
csrf = CSRFProtect()

def create_app():
    """Construct the core app object."""
    app = Flask(__name__, instance_relative_config=False)

    # Application Configuration
    app.config.from_object('config.Config')
    app.secret_key='aa'

    # Initialize plugins
    db.init_app(app)
    login_manager.init_app(app)
    csrf.init_app(app)

    with app.app_context():
        from . import routes
        from . import auth
        from .assets import compile_static_assets

        # Register Blueprints
        app.register_blueprint(routes.main_bp)
        app.register_blueprint(auth.auth_bp)

        # create database models
        db.create_all()

        # compile static assets
        if app.config['FLASK_ENV'] == 'development':
            compile_static_assets(app)

    return app

app/auth.py
"""Routes for user authentication."""
from flask import Blueprint, redirect, render_template, flash, request, session, url_for
from flask_login import login_required, logout_user, current_user, login_user
from .forms import LoginForm, SignupForm
from .models import db, User
from . import login_manager


# Blueprint configuration
auth_bp = Blueprint(
    'auth_bp',
    __name__,
    template_folder='templates',
    static_folder='static'
)



@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Log-in page for registered users.

    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """
    # if user already authenticated bypass
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('main_bp.dashboard'))
        flash('Invalid username or password')
        return redirect(url_for('auth_bp.login'))
    return render_template(
        'login.jinja2',
        form=form,
        title='Login',
        template='login-page',
        body="login with your user account."
    )


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    User sign-up page.

    GET request serve sign-up page.
    POST requests validate form & user creation.
    """
    form = SignupForm()
    if form.validate_on_submit():
        # check if user already exists
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            # build user object
            user = User(
                name=form.name.data,
                email=form.email.data,
                website=form.email.data
            )
            # set user password
            user.set_password(form.password.data)
            # create new user in database
            db.session.add(user)
            db.session.commit()
            # login the new user
            login_user(user)
            return redirect(url_for('main_bp.dashboard'))
        flash('A user already exists with that email address.')
    return render_template(
        'signup.jinja2',
        title='create an account',
        form=form,
        template='signup-page',
        body='Sign up for a user account.'
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None

@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login'))

app/routes.py
"""Logged-in page routes."""
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required, logout_user


# Blueprint Configuration
main_bp = Blueprint(
    'main_bp',
    __name__,
    template_folder='templates',
    static_folder='static'
)

@main_bp.route('/', methods=['GET'])
@login_required
def dashboard():
    """Logged-in User Dashboard"""
    return render_template(
        'dashboard.jinja2',
        title='Flask-login tutorial',
        template='dashboard-template',
        current_user=current_user,
        body="You are now logged-in"
    )


@main_bp.route('/logout')
@login_required
def logout():
    """User log-out login."""
    logout_user()
    return redirect(url_for('auth_bp.login'))

app/templates/dashboard.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
  <h1>{{ body }}</h1>

  {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('main_bp.logout') }}">Log out</a>
  {% endif %}

{% endblock %}

app/templates/layout.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <title>{{ title }}</title>
  <meta name="description" content="Add user authentication to your Flask app."/>
  <meta name="HandheldFriendly" content="True"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"/>
  <meta name="theme-color" content="#5eb9d7"/>
  <link rel="shortcut icon" href="{{ url_for('static', filename='dist/img/favicon.png') }}" type="image/x-icon"/>
  <meta property="og:site_name" content="Hackers and Slackers"/>
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="Hackers and Slackers - Hackers and Slackers"/>
  <meta property="og:description" content="Add user authentication to your Flask app."/>
  <meta property="og:url" content="https://flasklogin.hackersandslackers.app/"/>
  <meta name="twitter:title" content="{{ title }}"/>
  <meta name="twitter:description" content="Add user authentication to your Flask app."/>
  <meta name="twitter:url" content="https://flasklogin.hackersandslackers.app/"/>
  <meta name="twitter:site" content="@hackersslackers"/>
  <meta name="twitter:creator" content="@toddrbirchard"/>
  <meta name="twitter:card" content="summary_large_image"/>
  <meta name="twitter:image"
        content=" https://storage.googleapis.com/hackersandslackers-cdn/2019/06/flasklogin@2x.jpg"/>
  <meta property="og:image" content=" https://storage.googleapis.com/hackersandslackers-cdn/2019/06/flasklogin@2x.jpg"/>
  <meta property="og:image:width" content="1000"/>
  <meta property="og:image:height" content="523"/>
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet"/>
  {% block pagestyles %}{% endblock %}
</head>

<body class="{{ template }}">
<div class="container">
  {% block content %}{% endblock %}
</div>
<script src="{{ url_for('static', filename='dist/js/main.min.js') }}"></script>
{% block additionalscripts %}{% endblock %}
</body>

</html>

app/templates/login.jinja2
{% extends "layout.jinja2" %}

{% block content %}
  <div class="form-wrapper">
    <div class="logo">
      <img src="{{ url_for('static', filename='dist/img/logo.png') }}" alt="logo">
    </div>

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warring">
        <button type="button" class="close" data-dismiss="alert">
          x
        </button>
        {{ message }}
      </div>
    {% endfor %}

    <h1> Log in</h1>

    <form method="POST" action="/login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

      <fieldset class="email">
        {{ form.email.label  }}
        {{ form.email }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

      <div class="login-signup">
        <span>Don't have an account?</span>
        <a href="{{ url_for('auth_bp.signup') }}">Sign up.</a>
      </div>
    </form>
  </div>
{% endblock %}

app/templates/signup.jinja2
{% extends "layout.jinja2" %}



{% block content %}
    <div class="form-wrapper">
      
      <div class="logo">
        <img src="{{ url_for('static', filename='dist/img/logo.png') }}" alt="logo" />
    </div>

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warring">
        <button type="button" class="close" data-dismiss="alert">
          x
        </button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>Sign Up</h1>

    <form method="POST" action="/signup">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

      <fieldset class="name">
        {{ form.name.label }}
        {{ form.name(placeholder='John Smith') }}
        {% if form.name.errors %}
          <ul class="errors">
            {% for error in form.name.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="email">
        {{ form.email.label }}
        {{ form.email(placeholder='john@smith.com') }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="confirm">
        {{ form.confirm.label }}
        {{ form.confirm }}
        {% if form.confirm.errors %}
          <ul class="errors">
            {% for error in form.confirm.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="website">
        {{ form.website.label }}
        {{ form.website(placeholder='https://example.com') }}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>
    </form>

    <div class="login-signup">
      <div>
        <span>Already have an account?</span>
        <a href="{{ url_for('auth_bp.login') }}">Log in.</a>
      </div>
    </div>
{% endblock %}